/**
 * Auto-generated API documentation types and utilities
 * Generated: 2026-01-25T02:35:31.298Z
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 * Run `pnpm --filter @synatra/server generate:api-docs` to regenerate
 */

import indexData from "./api-docs-index.json"
import detailsData from "./api-docs-details.json"

export type ParamDef = {
  type: string
  description: string
  required?: boolean
}

export type EndpointIndex = {
  method: string
  path: string
  description: string
}

export type EndpointDetails = {
  method: string
  path: string
  pathParams?: Record<string, ParamDef>
  queryParams?: Record<string, ParamDef>
  bodyParams?: Record<string, ParamDef>
  responseExample: unknown
}

export type EndpointDoc = EndpointIndex & Omit<EndpointDetails, "method" | "path">

export const API_INDEX = indexData as Record<string, EndpointIndex[]>
export const API_DETAILS = detailsData as Record<string, EndpointDetails[]>

export function getIndex(type: string): EndpointIndex[] {
  return API_INDEX[type] ?? []
}

export function getDetails(type: string, method: string, path: string): EndpointDetails | null {
  const details = API_DETAILS[type] ?? []
  return details.find((d) => d.method === method && d.path === path) ?? null
}

export function formatIndexForLLM(index: EndpointIndex[]): string {
  return index.map((e, i) => `${i + 1}. ${e.method} ${e.path} - ${e.description}`).join("\n")
}

export function formatDetailsForLLM(details: EndpointDetails): string {
  const parts: string[] = [`${details.method} ${details.path}`]

  if (details.pathParams) {
    parts.push("\nPath Parameters:")
    for (const [name, def] of Object.entries(details.pathParams)) {
      parts.push(`  ${name}: ${def.type} - ${def.description}${def.required ? " (required)" : ""}`)
    }
  }

  if (details.queryParams) {
    parts.push("\nQuery Parameters:")
    for (const [name, def] of Object.entries(details.queryParams)) {
      parts.push(`  ${name}: ${def.type} - ${def.description}${def.required ? " (required)" : ""}`)
    }
  }

  if (details.bodyParams) {
    parts.push("\nBody Parameters:")
    for (const [name, def] of Object.entries(details.bodyParams)) {
      parts.push(`  ${name}: ${def.type} - ${def.description}${def.required ? " (required)" : ""}`)
    }
  }

  parts.push("\nResponse Example:")
  parts.push(JSON.stringify(details.responseExample, null, 2))

  return parts.join("\n")
}
